version: '3.9'

services:
  db:
    image: postgres:13.3
    restart: always
    container_name: postgresql_django
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "django_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  website:
    build: .
    links:
      - "db:database"
    restart: always
    container_name: website_django
    command: python pet_project/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_volume:
