version: '3'

services:
  db:
    image: postgres:13.3
    restart: always
    container_name: postgresql_django
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "django_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
#      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
  website:
    build: .
    restart: always
    container_name: website_django
    command: python pet_project/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
