version: '3.9'

services:
  db:
    image: postgres:13.3
    restart: always
    container_name: postgresql_django
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "django_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  website:
    build: .
    links:
      - "db:database"
    restart: always
    container_name: website_django
    command: bash -c "python pet_project/manage.py migrate 
                      && gunicorn --bind 0.0.0.0:8000 pet_project.website.wsgi"
    volumes:
      - ./media:/test-api/pet_project/media/
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    build: ./nginx
    container_name: nginx_django
    ports:
      - "80:80"
    depends_on:
      - website
    volumes:
      - ./media:/test-api/pet_project/media/

volumes:
  postgres_volume:
